# Generated by Django 2.0.12 on 2019-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0028_is_podcast_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_credits',
            field=models.CharField(
                default='',
                help_text='Vennligst oppgi kredittering for forsidebildet. Kreditteringen burde ha formatet "Foto: <navn>"',
                max_length=250,
                verbose_name='Bildekredittering'),
        ),
    ]
